# Generated by Django 4.2.7 on 2025-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carid', models.AutoField(db_column='carid', primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trimlevel', models.CharField(db_column='trimlevel', max_length=255)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('bodywork', models.CharField(max_length=20)),
                ('engine', models.IntegerField()),
                ('engine_capacity', models.CharField(max_length=3)),
                ('fuel', models.CharField(db_column='fuel', max_length=20)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
    ]
